name: TimeLimitDrop 自动构建

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github 
        settings-path: ${{ github.workspace }} 

    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: TimeLimitDrop
        path: target/TimeLimitDrop*.jar
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      if: success()
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "dev"
        prerelease: false
        title: "TimeLimitDrop 自动构建脚本"
        files: |
          target/TimeLimitDrop*.jar
